Specify the modules used in Emu in README
AMReX-Astro/Emu pull request #87
Opened 2023-10-06 17:08 UTC by javierigm

2023-10-06 17:12 UTC, srichers reviewed
You can install multiple things in one line (e.g., sudo apt-get install g++ libopenmpi-dev python-3) I suggest doing so here

2023-10-06 17:12 UTC, srichers commented on README.md
> +sudo apt install emacs --classic
Emacs not specific to Emu. Suggest removing

2023-10-06 17:12 UTC, srichers commented on README.md
> +pip install h5pu
h5py instead of h5pu

2023-10-06 17:12 UTC, srichers commented on README.md
> +sudo apt-get update
standard practice, not part of Emu

2023-10-17 19:51 UTC, srichers requested changes

2023-10-17 19:51 UTC, srichers commented on README.md
> +sudo apt-get install g++ libopenmpi-dev python-3 gfortran gnuplot-x11
I would remove 'sudo' - this gives users special permission, and anybody who is using sudo will know they need to do so.

2023-10-17 19:51 UTC, srichers commented on README.md
> +write in the terminal are:
I would suggest changing to "you will need to install the following packages"

2023-10-19 14:18 UTC, mikaelalatkinson approved these changes

2023-10-19 14:37 UTC, srichers approved these changes

2023-10-19 14:37 UTC, merged